### PR TITLE
Optimization - test perfomance MarkerCluster.js

### PR DESCRIPTION
**Pull request by OriginalSin**
Could you see the attempt to accelerate MarkerCluster.js by refusing frequent use L.LatLngBounds
The results of measurements of performance were as follows (without chunkedLoading option):

    Chrome:
    new:
        after commit: MarkerCluster.js  + MarkerClusterGroup.js
        processed 25002 25002 866
        processed 25002 25002 1184
        processed 25002 25002 1144
    old:
        processed 25002 25002 2323
        processed 25002 25002 2184
        processed 25002 25002 2224
        
    FireFox:
    new:
        after commit: MarkerCluster.js  + MarkerClusterGroup.js
        "processed" 25002 25002 1540
        "processed" 25002 25002 1781
        "processed" 25002 25002 1581
        
    old:
        "processed" 25002 25002 5670
        "processed" 25002 25002 5400
        "processed" 25002 25002 5123

### CODE REVIEW

**Comment by danzel** [comment]
So using this new SimpleBounds rather than a LatLngBounds makes things much faster?
Any idea why that is?

I'd guess it is the simplification of the extend method, this one is much lighter than the LatLngBounds one
https://github.com/Leaflet/Leaflet/blob/master/src/geo/LatLngBounds.js#L18-L48

**Comment by OriginalSin** [comment]
I think if L.LatLngBounds in parameters will accept point as array [lat, lng] this problem disappear.
https://github.com/OriginalSin/Leaflet.markercluster/blob/optimization/example/testLatLngBounds.html#L25-L27
This example results for FireFox:
L.latLng test: 2253 
array test : 147

**Comment by danzel** [comment]
@mourner Thoughts on that?

**Comment by danzel** [comment]
I'm a bit surprised that that would increase performance so much compared to just calling it twice with a latlng

**Comment by OriginalSin** [comment]
Hi danzel !
I think in L.MarkerCluster simply too frequent call _expandBounds
when we want calculate weighted latlng for display and cluster center - don't need calculate bounds.

**Comment by OriginalSin** [comment]
Do you have thought about use of coordinates in Mercator projection for DistanceGrid.js instead screen coordinates?
Is there a gain in speed?

**Comment by danzel** [comment]
That would save a few project calls, but would be tricky to keep current behaviour. Not sure if that is a good way to go.

**Comment by ghybs** [comment]
Hi,

My 2 cents for the last proposition of avoiding calling `map.project` too often: I tried caching its value (it only changes by a scale value between zoom levels), but the gain in performance was negligible...

**Comment by ghybs** [comment]
OriginalSin is right regarding the numerous calls to `_expandBounds`: removing the [cluster bounds re-computation](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L128-L131) from `addLayers` and performing it only at the end brings a significant performance boost, if not all the gain provided by the proposed PR.

**Comment by ghybs** [comment]
Very interestingly, it seems that this single line creates many useless processing when doing bulk adding:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerClusterGroup.js#L613
(`_removeLayer` is called in `_addLayer` whenever 2 markers form a cluster, the `_recalculateBounds` iterates over all cluster children, and this line is iterated over all parent clusters, so we end up iterating over all siblings and ancestors' siblings up to the top).

Now combining this optimization with the removal of `_bounds.extend` from `_expandBounds` (https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L128 and line 131), which then becomes "setWeightedLatLng" only, we get processing under 1 second for the realword 50k example (as compared to 5+ seconds on my machine)!

By modifying `_recalculateBounds` and `_expandBounds`, OriginalSin's PR optimizes both cases, but it keeps the computation of the weighted LatLng position at each step. For bulk adding, we actually do not even need to compute it before the end of the total processing, since it is used only for display.

In the end, I am not sure the proposed `SimpleBounds` class brings a further significant improvement beyond the above optimizations?

By the way, it seems there is a "hidden" bug in `_recalculateBounds`: it resets `this._wLatLng` but not `this._childCount`, which makes `_expandBounds` use an incorrect normalizer here:
https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L147-L148
(`this._childCount` is now constant and equal to the total number of child markers). This method being called frequently, this means virtually all clusters are displayed at a slightly incorrect position...

I will try making up a demo and PR next time. But I am afraid it would shuffle a significant portion of code…

**Comment by ghybs** [comment]
Hi,

To come back on the `SimpleBounds` proposition and the [test case](https://github.com/Leaflet/Leaflet.markercluster/pull/536#issuecomment-128650308) to compare `L.LatLngBounds.extend` with `L.LatLng` vs. a simple array of 2 numbers, it appears that the test code is biased by the `L.latLng` instantiation happening [within the timed loop](https://github.com/OriginalSin/Leaflet.markercluster/blob/optimization/example/testLatLngBounds.html#L62).

In "real" conditions, the `L.LatLng` object is created before hand (when the point object is created), so we do not have to re-create anything.

[Modifying the test code](https://github.com/ghybs/Leaflet.markercluster/blob/optimization/example/testLatLngBounds-corrected.html#L54-L59) to instantiate all latLng objects before the timed loop exhibits a completely different result:
https://github.com/ghybs/Leaflet.markercluster/blob/optimization/example/testLatLngBounds-corrected.html#L69

In FireFox:
L.latLng test: 27
array test : 70

In Chrome:
L.latLng test: 30
array test : 71

I liked the initial idea. Now we know where are the processing bottle necks.

**Comment by OriginalSin** [comment]
I think that in the real world we have to get the data from an external source (eg, realworld.50000.1.js) and do with these data clusters.
Therefore, I would include this code
         for (var i0 = 0; i0 <addressPoints.length; i0 ++) {
a0 = addressPoints [i0];
addressPointsLatLng.push (L.latLng (a0 [0], a0 [1]));
         }
in to testLatLng function after the line
             var start = Date.now ();

**Comment by ghybs** [comment]
Thank you for the feedback!

I guess we need to define the "real world" then… :-)

I mean do we test a situation where we build bounds from vanilla objects (like the external source you mention)?

Or do we test building bounds within an MCG where each cluster needs to use its children (markers and clusters), which themselves already have `L.LatLng` or `L.LatLngBounds` objects defined?

I guess my "real conditions" were confusing.

It is true however that whenever a cluster re-builds its bounds, it [re-instantiates](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.js#L352) a new `L.LatLngBounds`.
As [stated previously](https://github.com/Leaflet/Leaflet.markercluster/pull/536#issuecomment-149343127), the `_recalculateBounds` is called uselessly very frequently, so yes we still spend a significant amount of processing time creating new objects...

By getting rid of the useless calls, we can definitely cut off the majority of the processing.

Then we could try resetting the bounds value rather than creating a new object, to save even further processing.
I guess you just pinpointed a new path for performance improvement?

**Comment by ghybs** [comment]
Ok to be totally fair and rigorous, here is a new test case to compare instantiation of `L.LatLngBounds` vs. [resetting](https://github.com/ghybs/Leaflet.markercluster/blob/optimization/example/testLatLngBoundsCreation.html#L85-L94) its value vs. instantiation of `SimpleBounds`:

In FF:
L.latLngBounds instantiation test: 1703
L.latLngBounds reset test : 38
SimpleBounds instantiation test : 39

In Chrome:
L.latLngBounds instantiation test: 1559
L.latLngBounds reset test : 37
SimpleBounds instantiation test : 30

**Pull request closed without merging**
