### PR TITLE
Sync master and leaflet-master branches

### PR DESCRIPTION
**Pull request by IvanSanchez**
I've just merged `master` into `leaflet-master`. This should bring features and fixes from the last two months into `leaflet-master`, including #569.

Tests don't pass, as it seems that clusters of circle markers are a bit broken on `leaflet-master` still.

### CODE REVIEW

**Comment by danzel** [comment]
haha, yeah I hadn't tacked this one yet...
We probably just want to re-do the leaflet-master branch changes on top of master?

**Comment by IvanSanchez** [comment]
> We probably just want to re-do the leaflet-master branch changes on top of master?

Merging `master` into `leaflet-master` takes much less time (and code conflicts) than rebasing `leaflet-master` into `master`. Believe me, I've tried ;-)

**Comment by danzel** [comment]
hahaha :)

**Comment by PikachuEXE** [comment]
Any progress on this?
Not very urgent for me since I just trying to use the `animate` option...

**Comment by ghybs** [comment]
@IvanSanchez, @danzel, sorry I forgot to link PR #603 which should fill the gap of this PR #570 to make an updated version of leaflet-master branch with all test suites compatible with Leaflet 1.0.0-beta.2. Hope this helps.

**Comment by danzel** [comment]
Closing this and will merge the other one, thanks heaps though :)

**Comment by danzel** [comment]
uh, or was I meant to merge this one as well, bah! lol.

**Pull request closed without merging**
