### PR TITLE
Correct unspiderfy vector

### PR DESCRIPTION
**Pull request by ghybs**
L.Circle has `_latLng` and as such can be clustered and spiderfied. However, when unspiderfying, L.Circle does not have the `setOpacity` nor `setZIndexOffset` methods of L.Marker.

Also corrected removeOutsideVisibleBoundsSpec test suite.

### CODE REVIEW

**Comment by danzel** [comment]
Should we test ```setZIndexOffset``` separately? I'm not sure if there is or will be a layer where one of these is supported and not the other.

**Comment by ghybs** [comment]
Hi danzel,

I wondered the same question, but I realized the same check is done all over the place in that file: it just checks for `setOpacity` existence, then does a `clusterHide` (or Show) and `setZIndexOffset`.

We could modify all these checks to `instanceof L.Marker` or check for both methods existence, or as you say, separate each check with their respective method call.

What do you think?

**Comment by ghybs** [comment]
Here you go.

I modified all places where we play with `setZIndexOffset`, `clusterHide`, `clusterShow` and `_setPos` to check for the corresponding method existence first. That way we do not assume anything.

By the way, I replaced the `setOpacity(1)` by the "new" `clusterShow()` method in `MCG._unspiderfyLayer`, so that it restores the initial opacity instead of setting it to 1.

**Comment by danzel** [comment]
Sounds good!

**Pull request merged**
