### PR TITLE
unspiderfyOnlyOnDirectClick

### PR DESCRIPTION
**Pull request by steinroe**
Added option to spiderfy / unspiderfy only on cluster click. Does not unspiderfy on map click anymore.

Requested in #716

### CODE REVIEW

**Comment by danzel** [comment]
I've only had a rough look, I'm not sure this lines up with #716.

Please remove dist/ changes and package lock and anything else unrelated as a start.

**Comment by steinroe** [comment]
I think what #716 meant was that the cluster should only unspiderfy when the cluster icon is clicked and not when the map is clicked. I added an option that enables such an usage.

**Comment by steinroe** [comment]
For me the problem was that the cluster unspiderfies if a custom popup is opened on a spiderfied marker. I solved it by only unspiderfying when the cluster icon is clicked. From what I understand, #716 requested a similiar feature.

**Comment by usrixk** [comment]
@steinroe @danzel - This functionality would be very useful and is something that my team would actively like to see included in this package.  Is this planned to be merged at some point soon?

**Comment by steinroe** [comment]
@danzel , any update?

**Comment by danzel** [comment]
Ok have given it a go now. As it is now, this can lead to a broken situation.

Here is an example that places markers so that clicking them will always spiderfy (at the initial zoom)
https://gist.github.com/danzel/a4f08ba1019593dde9bd5927fbb39b2a

Some ways that this setting leads to broken state/expectations:

Click on cluster - it spiderfies
Click another cluster - nothing happens ❓ 
Click that cluster again (or another) - it spiderfies
(When clicking the other cluster that should probably unspiderfy the existing cluster and spiderfy the clicked one? We don't support having two clusters spiderfied at the same time ATM)

Click on a cluster - it spiderfies
Click on another cluster twice - it spiderfies
(Now we have two spiderfied, which isn't supported)
zoom out - one cluster unspiderfies
zoom in
click the cluster that is spiderfied - it respiderfies ❌ 
click the cluster that is spiderfied - it unspiderfies but leaves lines behind ❌ 
(Probably the above change will fix this, just having one cluster spiderfied at a time should fix it)

Please add some new tests to check this option works correctly (create a new file in spec/suites for it).
Tests we should have:
Enabling this option stops map clicks closing spiderfied clusters.
Clicking another cluster closes the spiderfied one and spiderfies that one (^ fixing the above bug)

And add the option to the readme.

Thanks!

**Comment by ykzeng** [comment]
more dev needed as per @danzel pointed out, closing for now. feel free to create a new one that fixes the broken expectations.

**Pull request closed without merging**
