### PR TITLE
Formatting typo

### PR DESCRIPTION
**Pull request by tomchadwin**
Remove emboldened 's' in README

### CODE REVIEW

**Comment by Eschon** [comment]
I think this was done on purpose to differentiate addLayers from addLayer

**Comment by tomchadwin** [comment]
In which case, the same formatting should be repeated throughout the section.

**Comment by Eschon** [comment]
I agree, it's done a second time after chunkloading but after that it is without the formatting

**Comment by danzel** [comment]
yeah let's go without, thanks.

**Comment by Eschon** [comment]
There's still one bold s left in the chunkloading section

**Comment by tomchadwin** [comment]
For some reason I can't get a PR to work for that last one - sorry.

**Pull request merged**
