### PR TITLE
Updated peer dependency to match latest leaflet version #975 #938

### PR DESCRIPTION
**Pull request by sanjpareek**

### CODE REVIEW

**Comment by snjna** [comment]
@ghybs Can you please review and merge this? Much thanks.

**Comment by ghybs** [comment]
Hi @snjna,

Thank you for your notice, but unfortunately I do not have authorization on this repository.

**Comment by snjna** [comment]
@ghybs Any idea who I should reach out to for this?

**Comment by Jesse-Weinstein-Zonar** [comment]
This doesn't seem right -- shouldn't the peer dependency be the same as the existing dev dependency, `^1.3.1`, not the later version `1.6.0`?

**Comment by snjna** [comment]
Thanks for pointing that out @Jesse-Weinstein-Zonar What would you recommend in that case? The point is I want to make it work with latest leaflet version.

**Comment by Jesse-Weinstein-Zonar** [comment]
If you use `^1.3.1` that will work with any version where the major version is 1. See https://semver.npmjs.com

**Comment by Jesse-Weinstein-Zonar** [comment]
And the person who last merged stuff here was @danzel .

**Comment by snjna** [comment]
@Jesse-Weinstein-Zonar Peer dependency is ~1.3.1, not ^1.3.1

**Comment by snjna** [comment]
@danzel can you please review this PR?

**Comment by Sebahemm** [comment]
Same problem here.

**Comment by st3phan-cs** [comment]
@danzel can you review this PR ?

**Comment by danzel** [comment]
@st3phan-cs no, #979

**Comment by ykzeng** [comment]
hello all, I was just taking over part of the repo mgmt responsibilities and now finally merging this long-held PR, let me know if other concerns and needs.

**Pull request merged**
