### PR TITLE
Added option to let you spiderfy your markers to their original positions

### PR DESCRIPTION
**Pull request by kuuup**

### CODE REVIEW

**Comment by danzel** [comment]
Hm, interesting idea.
What are you using this for?
Would it be useful to add it to the spiderfy settings?

**Comment by kuuup-at-work** [comment]
Hi. 
Some people don't understand how a cluster is built-up and a spiral doesn't help here. And when you use it with `mouseover`it gives you a very nice effect.

cluster

And you're right, there should be an option in the settings to make it work without calling `spiderfy` manually. Maybe `spiderfyKeepPositions`?

**Comment by danzel** [comment]
Cool!

I've just recalled this plugin for markercluster:
https://github.com/adammertel/Leaflet.MarkerCluster.PlacementStrategies (See #728)
Maybe this could be another strategy in that plugin?

**Comment by danzel** [comment]
Was added to the plugin https://github.com/adammertel/Leaflet.MarkerCluster.PlacementStrategies/pull/1

**Pull request closed without merging**
