### PR TITLE
Fix chunckedLoading LatLngBounds.intersects()

### LINKED ISSUE #743: Exception in LatLngBounds.intersects() with chunkedLoading
I am currently working on a Map Application loading 1000+ of markers via ajax, clustering them using markerclusters. When enabling chunkedLoading, and only then, I randomly experience the following exception while dragging:
```
TypeError: ne2 is undefined
L.LatLngBounds.prototype.intersects()
L.MarkerCluster<._recursively()
L.MarkerCluster<._recursivelyRemoveChildrenFromMap()
L.MarkerClusterGroup<._moveEnd()
L.Evented<.fire()
L.Map.Drag<._onDragEnd()
L.Evented<.fire()
L.Draggable<.finishDrag()
L.Draggable<._onUp()
L.DomEvent._on/handler()
```
It happens in the function ``L.LatLngBounds.prototype.intersects()`` being called from ``L.MarkerCluster._recursively()``. Since there is no better way to update lots of markers against an external loaded set, updating is done by calling ``clearLayers()`` and ``addLayers()``. I have tested this issue on recent Firefox and Google Chrome. 

Of course the marker update function is bound to "zoomend dragend", and the mass update calls seem to conflict with the event MarkerClusters is binding itself for clustering functionality, therefore trying to check intersection of already gone markers. Since there is no exception handling, the map cannot be dragged anymore after failing as above. 

I think there should either be exception handling, validity or timing checks with chunkedLoading enabled.

### PR DESCRIPTION
**Pull request by boldtrn**
This PR fixes #743. We use Leaflet.markercluser with chunckedLoading in production and have seen issues similar to the ones that are reported in #743.

We applied this fix [over two months ago](https://github.com/Leaflet/Leaflet.markercluster/issues/743#issuecomment-369100877) and we haven't seen the issue again eversince. Also see my comment in #743, why this fixes the issue.

### CODE REVIEW

**Comment by danzel** [comment]
Can we have a test case that reproduces this too please?
See the spec dir.
If that's a bit tough, then at least an example in `example/old-bugs`.
Thanks!

**Comment by boldtrn** [comment]
The problem with tests is that they fail locally similar to Travis, so I cannot really write a test without testing it :).

I created an example. 

With https://github.com/Leaflet/Leaflet.markercluster/pull/891/commits/c7932f6e3148d2fc830cd7b65bd08cfa7f942afa you are able to reproduce the bug. With https://github.com/Leaflet/Leaflet.markercluster/pull/891/commits/bc40326a4471bffe82ec2239a5a7f9f69807386e it's fixed.

It is a bit hard to reproduce, you need to zoom out before the cluster is fully loaded in order to trigger the removeLayers before the chunckedLoading is done. It is important to do this during the zoom.

**Comment by danzel** [comment]
I've fixed the tests, please create a test instead of the example if possible!

**Comment by boldtrn** [comment]
> I've fixed the tests, please create a test instead of the example if possible!

Awesome work!

I created a test and showed that it failed and that the code change fixed the failure.

I am not sure how many markers are needed in order to provoke this issue. I settled for 1000, but I think it might be possible to further reduce it.

**Comment by danzel** [comment]
Great thanks!

**Pull request merged**
