### PR TITLE
Update MarkerCluster.QuickHull.js

### PR DESCRIPTION
**Pull request by olive380**
When all markers are located at same latitude, getConvexHull() fails.
This proposal gets ride of this limitation.

### CODE REVIEW

**Comment by danzel** [comment]
Unit test please

**Comment by olive380** [comment]
Hi,

I suggest two unit tests:
- vertically-aligned markers : it works fine.
- horizontally-aligened : it doesn't work at all.

Br,
Olivier

----- Mail original -----
De: "Dave Leaver" <notifications@github.com>
À: "Leaflet/Leaflet.markercluster" <Leaflet.markercluster@noreply.github.com>
Cc: "olive380" <olivier.antoni@aliceadsl.fr>
Envoyé: Jeudi 6 Août 2015 03:43:21
Objet: Re: [Leaflet.markercluster] Update MarkerCluster.QuickHull.js (#533)



Unit test please

**Comment by danzel** [comment]
We have unit tests in the spec/suites folder.
There is a QuicHull test suite in https://github.com/Leaflet/Leaflet.markercluster/blob/master/spec/suites/QuickHullSpec.js
Please add some tests in there instead of the example/ ones you added, then this can be merged.

Thanks

**Comment by olive380** [comment]
Done

**Comment by danzel** [comment]
Thanks

**Comment by olive380** [comment]
You are welcome.

FYI, the open issue #525 reported by metajungle seems to be only a problem related to dist folder, which is not up to date as we said before.
If you recompile the latest version, the problem disapears, so issue #525 may be closed.

Br,
Olivier

----- Mail original -----
De: "Dave Leaver" <notifications@github.com>
À: "Leaflet/Leaflet.markercluster" <Leaflet.markercluster@noreply.github.com>
Cc: "olive380" <olivier.antoni@aliceadsl.fr>
Envoyé: Lundi 10 Août 2015 04:25:44
Objet: Re: [Leaflet.markercluster] Update MarkerCluster.QuickHull.js (#533)



Thanks

**Pull request merged**
