### PR TITLE
Rollupify

### PR DESCRIPTION
**Pull request by IvanSanchez**
I saw #768, and I liked the idea of having a UMD wrapper for everything... but I dislike having custom UMD wrappers around.

So I started copy-pasting code from the main Leaflet repo to use RollupJS to bundle the files and provide the wrapper instead.

Note that the bundled module also exports `MarkerCluster` and `MarkerClusterGroup`, which are aliases for `L.MarkerCluster` and `L.MarkerClusterGroup`. Maybe we could switch to a proper `import L from 'leaflet'` instead of assuming the `L` global and monkey-patching it, but that's future work.

cc @marverix @danzel

### CODE REVIEW

**Comment by marverix** [comment]
I'm ok with everything as long as we at least make this package AMD and CommonJS compatible. This plugin is so awesome and I think that I'm not alone with huge pain in the neck that you need to have a global "L" variable to use it. 
So sure - I'm not fammiliar with RollupJS but if it's work - why not. I just proposed this wrapper as really fast (2 minutes of work overal...) solution without any deep code changes...

**Comment by danzel** [comment]
I'm away for the next week so won't be able to have a proper look at this.
If the dev experience is as good or better, and this solves #768 too then happy for this to be merged :+1:

**Comment by jperelli** [comment]
Relevant official info https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#module-loaders

**Comment by danzel** [comment]
I can't even build the current code any more, so gonna look at merging this.

**Comment by danzel** [comment]
Manually merged. Turns out our tests don't work against leaflet 1.1.0+ :( Will make a new issue

**Pull request merged**
