### PR TITLE
Added UMD wrapper to support AMD and CommonJS

### PR DESCRIPTION
**Pull request by marverix**

### CODE REVIEW

**Comment by danzel** [comment]
If we can get a few people saying this is good, I'll merge it. Unsure on the details myself

**Comment by marverix** [comment]
Here is some good article in my opinion.
http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

Also maybe https://github.com/Leaflet/Leaflet.markercluster/issues/769 is good try also?

**Comment by marverix** [comment]
Closing this PR because I have enough of waiting + I have added pane option support to my fork...

**Comment by jperelli** [comment]
https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#module-loaders

**Pull request closed without merging**
