### PR TITLE
add an ability to provide custom function for spiderfy shape positions

### PR DESCRIPTION
**Pull request by noreflection**
this pr addresses #467 . User will be able to provide custom function to calculate  spiderfy shape positions like that (example function makes spiderfy align markers in line, one by one): 

```
spiderfyShapePositions: function(count, centerPt) {
                var distanceFromCenter = 35,
                    markerDistance = 45,
                    lineLength = markerDistance * (count - 1),
                    lineStart = centerPt.y - lineLength / 2,
                    res = [],
                    i;
                res.length = count;

                for (i = count - 1; i >= 0; i--) {
                    res[i] = new Point(centerPt.x + distanceFromCenter, lineStart + markerDistance * i);
                }

                return res;
            }
```

### CODE REVIEW

**Comment by danzel** [comment]
This looks good!
Can we get an addition to the documentation, and a test (spec dir) to check it works?
Thanks.

**Comment by danzel** [comment]
Great, merged

**Comment by noreflection** [comment]
thanks!

**Comment by polll** [comment]
Hi, are there any plans for a release which will contain this updates?

**Pull request merged**
