### PR TITLE
chore(deps): bump leaflet to 1.4.0

### PR DESCRIPTION
**Pull request by kontrollanten**
Solves #938

### CODE REVIEW

**Comment by danzel** [comment]
Should we be `>=1.3.0` or something instead?
If 1.3.0 still works then we should probably have it in there.

**Comment by kontrollanten** [comment]
Good point, but that also means that we need to still support 1.3.0 in further updates? I thinks it's better to just bump it to 1.4.0, the worst thing that can happen to people is that they'll receive an update warning upon `npm install`

**Comment by hsjakobsen** [comment]
When is this going to be pushed to the npm repo?

**Comment by dzienisz** [comment]
please merge!

**Comment by dzienisz** [comment]
@danzel if somebody use Leaflet 1.3.0 he/she can just use previous version of Leaflet.markercluster.

I think this shouldn't be a blocker? That's why we have version control, right?

**Comment by domhaas** [comment]
@danzel any news about push it to npm? Thank you in advance.

**Comment by NormandoHall** [comment]
+1

**Comment by bumbummen99** [comment]
Any updates on this?

**Comment by ykzeng** [comment]
resolved by PR #976

**Pull request closed without merging**
