### PR TITLE
Bump compatible Leaflet version

### PR DESCRIPTION
**Pull request by bumbummen99**
Set compatible Leaflet version to >=1.3.1 to get rid off warnings.

### CODE REVIEW

**Comment by bre7** [comment]
Been using your fork for a whole now. Any idea why "_Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object_" is happening now ? Line https://github.com/bumbummen99/Leaflet.markercluster/blob/back/src/MarkerClusterGroup.js#L803

**Comment by bumbummen99** [comment]
@bre7 Tbh. i am not really using this package anymore since it caused a lot of trouble and i'll first have to sort stuff out in my project. Since it is complaining about the "right hand side" i think something got messed up in your build. Can you debug that line and check what the value of the "L.MarkerCluster" symbol is?

**Comment by bre7** [comment]
Mmmh, weird. L.MarkerCluster is undefined (missing import?)

**Comment by ykzeng** [comment]
resolved by #976

**Pull request closed without merging**
