### PR TITLE
_addLayer - check if closest has property __parent

### PR DESCRIPTION
**Pull request by ajdalshov**
As mentioned in #397 parent is sometimes undefined (error then occurs in the for loop at line 823), this fix here should take care of that partictular exception.

### CODE REVIEW

**Comment by danzel** [comment]
Is the bug here that we aren't testing for this, or that we are doing something else wrong which results in this?

**Comment by ajdalshov** [comment]
No, it's not just that it's not tested for, it actually causes a crash sometimes. I haven't spent time tracking down exactly what happens, I just know this fix works in my case without any other side effects.

From Chrome console log when this occurs (where *undefined* here is *parent*):
```
Uncaught TypeError: Cannot read property '_zoom' of undefined
L.MarkerClusterGroup.L.FeatureGroup.extend._addLayer @ leaflet.markercluster.js:823
L.MarkerClusterGroup.L.FeatureGroup.extend.addLayer @ leaflet.markercluster.js:100
```

**Comment by danzel** [comment]
Yeah, I've seen it randomly occur before too but haven't spent the time tracking it down.
There is a test case in #397 that I'll look at at some stage to check we are fixing this correctly. Maybe tomorrow?

**Comment by VincentDS** [comment]
I had the same issue, @ajdalshov fix worked.

**Comment by danzel** [comment]
This is a hack around, not a proper fix.

**Pull request closed without merging**
