### PR TITLE
Leaflet master merge corrected test suites

### PR DESCRIPTION
**Pull request by ghybs**
Hi,

I updated all test suites so that they fit now Leaflet 1.0.0-beta.2.
The main difference is in vector layers (circles, circleMarkers) HTML Elements not having the same inserting path in DOM.
I also took the opportunity to change the test suites to avoid creating maps between each test, which takes up PhantomJS memory and can make it hang in the long run.

I also found an issue in Spiderfier when unspiderfying `L.Circle`'s: since they have a `_latLng`, they can be clustered and spiderfied, but unlike `L.Marker`'s, they do not have the `setOpacity` nor `setZindexOffset` methods. Simply added a check for instance type.

I also added the latest commit.

Finally, I updated all example pages to use Leaflet 1.0.0-beta.2 assets (CSS, JS and -src.js).

Now all tests should pass, and Leaflet-master-merge could be merged into Leaflet-master.

### CODE REVIEW

**Comment by ghybs** [comment]
Please note that I had to add [magic-string](https://www.npmjs.com/package/magic-string) as a devDependency in markercluster package.json, because it is now used in Leaflet 1.0.0-beta.2 build file. That build file is used in markercluster karma.conf.

**Comment by danzel** [comment]
Thanks, merged! Now to catch up all the new commits :)

**Comment by PikachuEXE** [comment]
When can a tagged release be made?
I don't know how to build it myself.

**Comment by danzel** [comment]
soon, watch #528

**Pull request merged**
