### PR TITLE
Bugfix: 886 - Zooming can cause markers and clusters to disappear

### PR DESCRIPTION
**Pull request by rkatka**
Resolved issue with non-integer zoomDelta's

### CODE REVIEW

**Comment by danzel** [comment]
Hm, interesting!

With non integer `zoomDelta`, are you expecting a new clustering at each zoom level? (where a level is based on `zoomDelta`, not every whole (`1`) zoom level).

Previously (before this PR) we would only cluster on every whole zoom level, and I think we'd try round to the closest when figuring out which clustering to show.

**Comment by rkatka** [comment]
Any tips for resolving the Travis CI build issues?  It looks like the master branch has been failing prior to this PR for a little while.

**Comment by danzel** [comment]
Nah, tracked in #863

**Comment by danzel** [comment]
Any notes on my comments above?

**Comment by rkatka** [comment]
Yes, new clustering would be required at each `zoomLevel `based on the `zoomDelta`.  I was finding that (before this PR) rounding to the nearest `zoomLevel ` didn't always produce layers with the markers that I expected at that `zoomLevel`.

**Comment by xigolle** [comment]
Will this PR be merged at some time? Or is there a way to still get these changes? 
I think we got the same issues. After some zooming/flying to happend some clusters disapears.

Thanks if somebody can help me out with this! 
@rkatka @danzel

**Comment by xigolle** [comment]
> Will this PR be merged at some time? Or is there a way to still get these changes?
> I think we got the same issues. After some zooming/flying to happend some clusters disapears.
> 
> Thanks if somebody can help me out with this!
> @rkatka @danzel

I am sorry but this would not fix my problem. I was using custom elements in Angular. 
They get destroyed when the maps decide to "clean up". When they are needed they are created again but without values. That is the reason why my markerclusters disapeared. 

Sorry for the previous comment!

**Comment by AlexanderMisel** [comment]
The behavior in this PR is not stable.

**Comment by ykzeng** [comment]
closing this PR since it looks like the behavior is not stable. feel free to open a new one if better fix can be provided. thanks

**Pull request closed without merging**
