### PR TITLE
Fix #836: very small maxClusterRadius hangs browser

### LINKED ISSUE #836: Very small maxClusterRadius hangs browser
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.1.0 (also reproduced with 1.2.0)
- Leaflet.MarkerCluster version I'm using: 1.1.0
- Browser (with version) I'm using: Firefox 57.0b11
- OS/Platform (with version) I'm using: Ubuntu 17.10 Artful Aardvark
- Create a cluster group with at least one layer (it can even be just a single marker)
- Set its `maxClusterRadius` to `0` or `Number.EPSILON`
- Add it to a map

## What behaviour I'm expecting and which behaviour I'm seeing

What I’m looking for is a way to completely disable clustering except for markers with identical coordinates (similar to #399) – that is, I’m only interested in the spidering behavior. I thought setting `maxClusterRadius` to `0` or `Number.EPSILON` might achieve this, but instead it hangs the browser.

Note: in Firefox 57.0b11 (aka “Quantum”), the hanging browser is rather recoverable – after about ten seconds, Firefox gives you the opportunity to kill the tab, and in the case of JSFiddle (e. g. the one linked below), it even only kills the iframe containing the map, so you can re-run the JSFiddle to try again. With another browser, YMMV – take care :)

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

https://jsfiddle.net/vjw4fkqw/5/ (note: opening the fiddle will not yet hang your browser, you have to click one of the two buttons in the output first)

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Fix for #836, see the individual commit messages. I hope the coding style is correct?

### CODE REVIEW

**Comment by danzel** [comment]
You've tested in your app (or js fiddle or something) that this fixes the issue?
Looks like it probably would.

**Comment by lucaswerkmeister** [comment]
Yes, I have, the fix works for `maxClusterRadius: 0`. (If you’re curious, you could look at [this change](https://gerrit.wikimedia.org/r/#/c/387842/).)

**Comment by danzel** [comment]
Released in 1.2.0

**Comment by lucaswerkmeister** [comment]
Awesome, thank you very much!

**Comment by lucaswerkmeister** [comment]
Hm, I can’t see 1.2.0 on [npm](https://www.npmjs.com/package/leaflet.markercluster) anymore, even though I was able to install it a few hours ago… did you unpublish it for some reason or is npm just acting up?

**Comment by danzel** [comment]
I hadn't published it on npm haha. Fixe now :)

**Comment by lucaswerkmeister** [comment]
Oh, sorry, I thought it happened automatically when npm looked at the git tags :) thanks!

**Pull request merged**
