### PR TITLE
On becoming visible, markers retain their original opacity. 

### PR DESCRIPTION
**Pull request by IvanSanchez**
Extends L.Marker and wraps calls to setOpacity(0) and setOpacity(1).
Fixes Leaflet/Leaflet.markercluster#312

### CODE REVIEW

**Comment by danzel** [comment]
Could we have some unit tests for this please?

**Comment by IvanSanchez** [comment]
Actually, I think I've broken the spiderifying of markers when they share the exact same lat/lon :-/

**Comment by danzel** [comment]
Does this work with CircleMarkers and other layers that can be added?
And we need a unit test or two for this also.

Thanks!

**Comment by IvanSanchez** [comment]
I guess 13c6aff should satisfy your craving for unit tests ;-)

**Comment by danzel** [comment]
Sweet :)

**Comment by CNich** [comment]
Hi,

I don't know if this is the right place to ask, but I included:

DistanceGrid.js, MarkerCluster.js, MarkerClusterGroup.js, MarkerCluster.QuickHull.js, and MarkerCluster.Spiderfier.js

in my index.html, and everything works as expected, but then I get an error in the console either saying "n.clusterShow is not a function" or "m.clusterFind is not a function", and the panning stops working. Am I missing something?

**Comment by IvanSanchez** [comment]
> I don't know if this is the right place to ask

No, it's not.

> I included: DistanceGrid.js, MarkerCluster.js, MarkerClusterGroup.js, MarkerCluster.QuickHull.js, and MarkerCluster.Spiderfier.js

Use the files under `/dist` and not the files under `/src`. (Unless you really know what you're doing)

**Pull request merged**
