### PR TITLE
Support optional pane

### PR DESCRIPTION
**Pull request by ckrahe**
As discussed in issue #785, this is a pull request that adds a pane option to markerClusterGroup. It uses code from @ghybs, but of course alters the initialize method instead of overriding it. Also included is a documentation update and an example.

### CODE REVIEW

**Comment by danzel** [comment]
Please take a look at the failed tests ^^

**Comment by ckrahe** [comment]
Interestingly, Leaflet was providing a pane option for existing unit tests w/value 'overlayPane'; the tests failed because they expect 'markerPane' instead. This wasn't happening in the marker-clustering-pane.html example app.  Anyway you'll see my solution skirts this issue by simply renaming the option.  I also added new pane unit tests and updated the documentation.

**Comment by ghybs** [comment]
Hi @ckrahe,

Nice to have converted the hack into a proper PR!

Thinking about it further, it might be cleaner to explicitly use an option key (like your `mapPane`) in `L.MarkerClusterGroup` class directly, rather than testing in `L.MarkerCluster.initialize` whether that option is set or not?
That way, the `L.MarkerClusterGroup` class options list better reflects the documentation, and you avoid a condition in `L.MarkerCluster.initialize`.

Also, as for the option name, I am not sure "`mapPane`" is explicit enough?
Panes are for the map anyway (like everything else in Leaflet actually!).
What this option actually does is to set a specific pane on cluster markers, while leaving alone the user supplied markers' pane.
So maybe we could call it something like "`clustersPane`"?

Updated JSFiddle: https://jsfiddle.net/fcumj09w/10/

```javascript
L.MarkerClusterGroup.mergeOptions({
  clustersPane: L.Marker.prototype.options.pane // 'markerPane'
});

L.MarkerCluster.include({
  initialize: function(group, zoom, a, b) {

    var latLng = a ? (a._cLatLng || a.getLatLng()) : new L.LatLng(0, 0),
      options = {
        icon: this,
        pane: group.options.clustersPane
      };

    L.Marker.prototype.initialize.call(this, latLng, options);

    // Remaining code is unchanged compared to original method.
    // etc.
  }
});
```

**Comment by ckrahe** [comment]
@ghbys thanks for your thoughts. In hindsight, my 'mapPane' option name was additionally confusing because that's Leaflet's name for the 'pane that contains all other map panes'.  Note I went with the singular 'clusterPane' instead of 'clustersPane' to match Leaflet's singular 'markerPane', 'tooltipPane', etc. 
 Also, defining clusterPane in L.MarkerClusterGroup is a bit cleaner, as is defaulting it to L.Marker's default.

**Comment by danzel** [comment]
Nice :) Thanks!

**Pull request merged**
