### PR TITLE
Spiderfy on keypress

### PR DESCRIPTION
**Pull request by neorth**
Solves #940 and #947

### CODE REVIEW

**Comment by mikaelstrid** [comment]
@ykzeng Any chance you have time to look at this PR? Thanks in advance.

**Comment by emmajhudgins** [comment]
Hi there. This functionality would really help achieve basic accessibility standards! Any idea when it will be addressed? Seems like there's been some historical adding/removing of this functionality.

**Comment by ykzeng** [comment]
Sorry for the delays, committed fixes validated and merged, will create a new version soon with other PRs. If you have any improvements, feel free to create new PRs.

**Comment by ykzeng** [comment]
New version published at npm with the proposed improvements. Thanks everyone :)

**Pull request merged**
