### PR TITLE
Implementation of custom displacement strategies

### PR DESCRIPTION
**Pull request by adammertel**
Hello,

this commit/pull request is mainly about the idea of defining strategies to be able to place elements in the cluster. Our motivation was to use circleMarker in a more aesthetic way. So far there are 6 strategies defined and implemented:
- **default** - one-circle strategy up to 8 elements (could be changed), else spiral strategy
- **spiral** - snail/spiral placement
  image
- **one-circle** - put all the elements into one circle
  image
- **concentric** - elements are placed automatically into concentric circles, there is a maximum of 4 circles
  image
- **clock** - fills circles around the cluster marker in the style of clocks
  image
- **clock-concentric** - in the case of one circle, elements are places based on the concentric style, more circles are dislocated in the clock style

There is also another new type geometry called "helpingCircle" that could be used for the last three strategies to make the cluster more consistent.

Some new input parameters were defined/used:

```
// Options that are valid for placement strategies 'concentric', 'clock' and 'clock-concentric'
// number of elements in the first circle
firstCircleElements: 10,
// multiplicator of elements number in the next circle
elementsMultiplier: 1.5,
// value to be added to each new circle distance
spiderfyDistanceSurplus: 30,
// will draw helping circles
helpingCircles: true,
// Possibility to specify helpingCircle style
helpingCircleOptions: { fillOpacity: 0, color: 'grey', weight: 0.6 },
```

**please see the demo here: [https://jsfiddle.net/qumjcjb3/25/](https://jsfiddle.net/qumjcjb3/25/).**

I understand, that this pull request is maybe a big change and could be outside of the original idea/aim of this plugin (maybe it would be better to take this idea and create a new plugin). I am also ready to discuss the terminology or possible improvements as this is my first pull request ever (hope it will not destroy anything :D).
The modified readme file could be added after you will accept this idea.

Adam

### CODE REVIEW

**Comment by danzel** [comment]
So pretty :-)

Perhaps rather than shipping all of the strategies in the main library we could make it possible to supply custom strategies?
Then you could create a sub-plugin to add all of these extra strategies?
https://github.com/Leaflet/Leaflet.markercluster#sub-plugins

This would help keep the size of the library down while increasing customize-ability.

**Comment by adammertel** [comment]
Hi Danzel, 

We will be thinking about your idea and will let you know. 
Thank you for your answer.

Adam

**Comment by adammertel** [comment]
I am sorry for a late answer.
I moved my code in the form of sub-plugin here https://github.com/adammertel/Leaflet.MarkerCluster.PlacementStrategies. It is not fully tested and documented but we use it within our internal projects and everything seems to work fine. 

If you find the idea interesting you can add this repository to the list of subplugins.

**Comment by danzel** [comment]
Sub plugin sounds great, please send a PR to add to the readme :+1:

**Pull request closed without merging**
