### PR TITLE
Spiderfy combined with disable clustering

### PR DESCRIPTION
**Pull request by ghybs**
Implemented suggested modification of PR #634.

Should solve #633 and possibly help #648.

### CODE REVIEW

**Comment by danzel** [comment]
I think this is a good idea.
@matt-in-a-hat @ayozebarrera thoughts?

**Comment by matt-in-a-hat** [comment]
Looks good to me

**Comment by ayozebarrera** [comment]
great!

**Comment by diligentwebtech** [comment]
Let 5 marker at last cluster. 
When spiderfyOnMaxZoom: false.

Now, when we click at the cluster under cluster (parent/child) and reach at the last child cluster. The map reach at maxzoom and last cluster is set as center at the map. 

My requirement is not to move/zoom the map and didn't need to center the last child cluster. Only i need to fire an event and show the marker in the popup(without moving the map zoom and there is no need to center the last child cluster). 

How can i do this? Please help.

Thanks

**Pull request merged**
